version: '3.9'

volumes:
  db-data:
    external: false

services:
  db: 
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports: 
      - "5432:5432"
    volumes: 
      - db-data:/usr/local/pgsql/data  
  
  web:
    build: .
    ports:
      - "3000:3000"
